SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MatchupEntries](
	[id] [int] IDENTITY(1,1) NOT NULL,
    [MatchupID] [int] NOT NULL,
	[ParentMatchupID] [int] NOT NULL,
    [TeamCompetingID] [int] NOT NULL,
    
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MatchupEntries] ADD  CONSTRAINT [Pk_MatchupEntries] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
