SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TeamMembers](
    [id] [int] IDENTITY(1,1) NOT NULL,
    [TeamID] [int] NOT NULL,
    [PearsonID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TeamMembers] ADD  CONSTRAINT [Pk_TeamMembers] PRIMARY KEY CLUSTERED 
(
    [id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
