//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPLTournament {
	
	
	public partial class CreateTournament {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.DropDownList SelectTeam;
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.WebControls.Button AddTeamBtn;
		
		protected System.Web.UI.WebControls.ListBox TeamPlayerList;
		
		protected System.Web.UI.WebControls.Button DeleteTeamBtn;
		
		protected System.Web.UI.HtmlControls.HtmlForm form3;
		
		protected System.Web.UI.WebControls.Button AddPrizeBtn;
		
		protected System.Web.UI.WebControls.ListBox PrizeList;
		
		protected System.Web.UI.WebControls.Button DeletePrizeBtn;
		
		protected System.Web.UI.HtmlControls.HtmlForm form4;
		
		protected System.Web.UI.WebControls.Button CreateTournamentSubmit;
	}
}
