//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPLTournament {
	
	
	public partial class TournamentView {
		
		protected System.Web.UI.HtmlControls.HtmlForm form3;
		
		protected System.Web.UI.WebControls.DropDownList RoundList;
		
		protected System.Web.UI.HtmlControls.HtmlForm form4;
		
		protected System.Web.UI.WebControls.CheckBox UnplayedOnly;
		
		protected System.Web.UI.HtmlControls.HtmlForm form5;
		
		protected System.Web.UI.WebControls.ListBox MatchupListbox;
		
		protected System.Web.UI.HtmlControls.HtmlInputText Score1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText Score2;
		
		protected System.Web.UI.HtmlControls.HtmlForm form6;
		
		protected System.Web.UI.WebControls.Button Score;
	}
}
